[tool.poetry]
name = "uvp-interactive-web"
version = "0.1.0"
description = ""
authors = ["Gary Tyler <mail@garytyler.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.54.1"
ujson = "^2.0.3"
itsdangerous = "^1.1.0"
python-multipart = "^0.0.5"
emailvalidator = "^0.3"
aioredis = "^1.3.1"
python-slugify = "^4.0.0"
tortoise-orm = "^0.16.5"

[tool.poetry.dev-dependencies]
uvicorn = "^0.11.5"
flake8 = "^3.7.9"
black = {version = "^19.10b0", allow-prereleases = true}
mypy = "^0.770"
pytest = "^5.4.1"
pytest-asyncio = "^0.10.0"
asgi-lifespan = "^1.0.0"
websockets = "^8.1"
isort = "^4.3.21"
async-asgi-testclient = "^1.4.4"
pytest-xprocess = "^0.13.1"
httpx = "^0.12.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
